apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  # Define the pod here:
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: mern-app-stack-client
          imagePullPolicy: Never
          # This is actually incorrect. REACT_APP_YOUR_HOSTNAME should be passed as an argument to the image's Dockerfile when building. This is post-build-time, and so importing the ConfigMap from example-env is practically redundant:
          envFrom:
            - configMapRef:
                name: example-env
          ports:
            - containerPort: 3000

