apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  # Define the pod here:
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: mern-app-stack-api
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: example-env
          ports:
            - containerPort: 5000

